//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@interface WWKAttendanceBinaryCheckViewController : UIViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate>

//- (void)p_openCamera:(scoped_refptr_e21d2ae3)arg1;
//- (void)p_openCamera_V27:(Promise_dd2761d8 *)arg1;

@end

